import { z } from 'zod';
const enc=new TextEncoder();
export const digest=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
export const constantEqual=(a:string,b:string)=>{let mismatch=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)mismatch|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return mismatch===0};
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('');
export async function passwordHash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bytes=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations:100000},key,256);return Array.from(new Uint8Array(bytes)).map(x=>x.toString(16).padStart(2,'0')).join('')}
export const cookieToken=(r:Request)=>r.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('__Host-prism='))?.slice(13)||'';
const cookie=(token:string,age:number)=>`__Host-prism=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${age}`;
export async function sessionOwner(r:Request,d:D1Database){const token=cookieToken(r);if(!token)return null;const s=await d.prepare('SELECT owner FROM sessions WHERE id=? AND expires>?').bind(await digest(token),Math.floor(Date.now()/1000)).first<{owner:string}>();return s?.owner||null}
async function limit(r:Request,d:D1Database){const now=Math.floor(Date.now()/1000),id=await digest('login:'+(r.headers.get('cf-connecting-ip')||'unknown'));await d.prepare('INSERT INTO auth_attempts (id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END,expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END').bind(id,now+900,now,now).run();const row:any=await d.prepare('SELECT count FROM auth_attempts WHERE id=?').bind(id).first();return {id,allowed:row.count<=10}}
export async function auditRecord(d:D1Database,owner:string,category:string,action:string,detail:string,server=''){await d.prepare('INSERT INTO audit (id,owner,server,time,category,action,detail) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),owner,server,Math.floor(Date.now()/1000),category,action,detail).run()}
export async function authPublic(r:Request,path:string,d:D1Database,mode:string){if(path==='auth/status'&&r.method==='GET'){const row=mode==='token'?await d.prepare("SELECT username FROM accounts WHERE owner='admin'").first():null;return Response.json({mode,passwordConfigured:!!row})}if(!path.startsWith('auth/'))return null;if(mode!=='token')return Response.json({error:'这里使用 ChatGPT 登录；独立密码仅用于自托管部署。'},{status:400});if(path==='auth/login'&&r.method==='POST'){const gate=await limit(r,d);if(!gate.allowed)return Response.json({error:'登录尝试过多，请在 15 分钟后再试。'},{status:429});const data=z.object({username:z.string().min(1).max(64),password:z.string().min(1).max(128)}).parse(await r.json());const row:any=await d.prepare('SELECT * FROM accounts WHERE username=?').bind(data.username.toLowerCase()).first();const candidate=await passwordHash(data.password,row?.salt||'prism-invalid-user-constant-salt');if(!row||!constantEqual(candidate,row.password))return Response.json({error:'用户名或密码不正确'},{status:401});const token=random(),now=Math.floor(Date.now()/1000);await d.batch([d.prepare('INSERT INTO sessions(id,owner,expires) VALUES (?,?,?)').bind(await digest(token),row.owner,now+604800),d.prepare('DELETE FROM auth_attempts WHERE id=?').bind(gate.id),d.prepare('DELETE FROM sessions WHERE expires<?').bind(now)]);await auditRecord(d,row.owner,'security','密码登录','成功建立 7 天登录会话');return Response.json({ok:true},{headers:{'Set-Cookie':cookie(token,604800),'Cache-Control':'no-store'}})}return null}
export async function authPrivate(r:Request,path:string,d:D1Database,o:string,mode:string){if(!path.startsWith('auth/'))return null;if(mode!=='token')return Response.json({error:'ChatGPT 账号密码由登录平台管理。'},{status:400});if(path==='auth/logout'&&r.method==='POST'){await d.prepare('DELETE FROM sessions WHERE id=? AND owner=?').bind(await digest(cookieToken(r)),o).run();await auditRecord(d,o,'security','退出登录','当前会话已撤销');return Response.json({ok:true},{headers:{'Set-Cookie':cookie('',0)}})}if((path==='auth/password'||path==='auth/setup')&&r.method==='POST'){const data=z.object({username:z.string().min(3).max(64).regex(/^[A-Za-z0-9_.-]+$/).optional(),password:z.string().min(12).max(128),currentPassword:z.string().max(128).optional()}).parse(await r.json());const old:any=await d.prepare('SELECT * FROM accounts WHERE owner=?').bind(o).first();if(old&&path==='auth/setup')return Response.json({error:'密码已设置，请使用修改密码功能。'},{status:409});if(!old&&path==='auth/password')return Response.json({error:'请先设置登录密码。'},{status:400});if(old){const gate=await limit(r,d);if(!gate.allowed)return Response.json({error:'尝试过多，请稍后重试。'},{status:429});if(!constantEqual(await passwordHash(data.currentPassword||'',old.salt),old.password))return Response.json({error:'当前密码不正确'},{status:403})}const salt=random(),username=(data.username||old?.username||'admin').toLowerCase(),value=await passwordHash(data.password,salt);await d.batch([d.prepare('INSERT INTO accounts(owner,username,salt,password,changed) VALUES (?,?,?,?,?) ON CONFLICT(owner) DO UPDATE SET username=excluded.username,salt=excluded.salt,password=excluded.password,changed=excluded.changed').bind(o,username,salt,value,Math.floor(Date.now()/1000)),d.prepare('DELETE FROM sessions WHERE owner=?').bind(o)]);await auditRecord(d,o,'security',old?'修改密码':'设置密码','密码已安全更新；所有旧会话已失效');return Response.json({ok:true},{headers:{'Set-Cookie':cookie('',0),'Cache-Control':'no-store'}})}return null}
