import {countryName} from './model';
const cities:Record<string,string>={'Los Angeles':'洛杉矶','San Jose':'圣何塞','San Francisco':'旧金山','New York':'纽约','Chicago':'芝加哥','Dallas':'达拉斯','Seattle':'西雅图','Ashburn':'阿什本','Tokyo':'东京','Osaka':'大阪','Singapore':'新加坡','Hong Kong':'香港','Frankfurt am Main':'法兰克福','Frankfurt':'法兰克福','London':'伦敦','Paris':'巴黎','Amsterdam':'阿姆斯特丹','Seoul':'首尔','Taipei':'台北','Sydney':'悉尼','Toronto':'多伦多','Vancouver':'温哥华','Berlin':'柏林','Helsinki':'赫尔辛基','Stockholm':'斯德哥尔摩','Mumbai':'孟买','San Antonio':'圣安东尼奥','Phoenix':'凤凰城','Dubai':'迪拜'};
const operators:Record<string,string>={'AT&T':'AT&T 美国电话电报','NTT':'NTT 日本电信','HETZNER':'Hetzner 德国海岑纳','SINGTEL':'新加坡电信','CHINANET':'中国电信','CHINA TELECOM':'中国电信','CHINA MOBILE':'中国移动','CHINA UNICOM':'中国联通','COMCAST':'康卡斯特','AMAZON':'亚马逊 AWS','GOOGLE':'谷歌云','MICROSOFT':'微软 Azure','BRITISH TELECOM':'英国电信 BT','ORACLE':'甲骨文 Oracle 云','OVH':'法国 OVH 云','DIGITALOCEAN':'DigitalOcean 云','CLOUDFLARE':'Cloudflare 网络','AKAMAI':'阿卡迈 Akamai'};
export function operatorName(name:string){const match=Object.keys(operators).find(k=>name.toUpperCase().includes(k));return match?operators[match]:name||'待识别'}
export function networkType(org:string){
 if(/AMAZON|GOOGLE|MICROSOFT|ORACLE|OVH|HETZNER|DIGITALOCEAN|LINODE|VULTR|CLOUDFLARE|AKAMAI/i.test(org))return '数据中心 / 云网络（ASN 推测）';
 if(/AT&T|COMCAST|CHARTER|VERIZON|CHINANET|CHINA TELECOM|CHINA MOBILE|CHINA UNICOM|BRITISH TELECOM|SINGTEL/i.test(org))return '接入运营商（家宽待核验）';
 if(/NTT|COGENT|LUMEN|LEVEL ?3|TELIA|ARELION/i.test(org))return '骨干 / 企业网络（家宽待核验）';
 return '网络类型待核验';
}
function publicIp(ip:string){return /^[0-9a-f:.]+$/i.test(ip)&&! /^(127\.|10\.|192\.168\.|169\.254\.|0\.|172\.(1[6-9]|2[0-9]|3[01])\.|::|f[cd]|fe[89ab])/i.test(ip)}
export async function locate(r:Request,c:any){const cf=(r as any).cf||{},ip=r.headers.get('cf-connecting-ip')||'',country=cf.country||r.headers.get('cf-ipcountry');let geo:any={ip,operator:operatorName(cf.asOrganization||''),asn:cf.asn?'AS'+cf.asn:'',source:cf.country?'Cloudflare 请求地理信息':'来源 IP（尚未配置定位服务）',confidence:'IP 地理数据库；不证明住宅属性',broadcast:'广播 / 原生属性待核验',network:networkType(cf.asOrganization||''),geoCheckedAt:Math.floor(Date.now()/1000)};if(country&&/^[A-Z]{2}$/.test(country))geo.country=country;if(cf.latitude&&cf.longitude){geo.latitude=Number(cf.latitude);geo.longitude=Number(cf.longitude);geo.locationAccuracy='IP 城市级近似'}geo.region=country?countryName(country)+(cities[cf.city]?' · '+cities[cf.city]:''):'待识别';if(ip&&c.ipinfoToken){try{const res=await fetch(`https://ipinfo.io/${encodeURIComponent(ip)}/json?token=${encodeURIComponent(c.ipinfoToken)}`,{signal:AbortSignal.timeout(5000)});if(res.ok){const d:any=await res.json();if(d.country)geo.country=d.country;geo.region=countryName(geo.country||'ZZ')+(cities[d.city]?' · '+cities[d.city]:'');geo.operator=operatorName(String(d.org||cf.asOrganization||''));geo.asn=String(d.org||'').match(/AS\d+/)?.[0]||geo.asn;const loc=String(d.loc||'').split(',').map(Number);if(loc.length===2&&loc.every(Number.isFinite)){geo.latitude=loc[0];geo.longitude=loc[1];geo.locationAccuracy='IP 城市级近似'}geo.network=d.company?.type==='hosting'?'数据中心（数据库识别）':d.company?.type==='isp'?'接入运营商（住宅待核验）':'网络类型待核验';geo.source='IPinfo / '+new Date().toISOString().slice(0,10)}}catch{}}if(!c.ipinfoToken&&publicIp(ip)&&!cf.asn){try{const res=await fetch(`https://ipwho.is/${encodeURIComponent(ip)}`,{signal:AbortSignal.timeout(5000)});if(res.ok){const d:any=await res.json();if(d.success===true){const org=String(d.connection?.isp||d.connection?.org||'');geo.operator=operatorName(org);geo.asn=d.connection?.asn?'AS'+d.connection.asn:'';geo.network=networkType(org+' '+String(d.connection?.org||''));if(/^[A-Z]{2}$/.test(d.country_code))geo.country=d.country_code;geo.region=countryName(geo.country||'ZZ')+(d.city?' · '+(cities[d.city]||d.city):'');if(typeof d.latitude==='number'&&typeof d.longitude==='number'){geo.latitude=d.latitude;geo.longitude=d.longitude;geo.locationAccuracy='IP 城市级近似'}geo.source='IPWHOIS 免费 IP 数据库';geo.confidence='运营商来自 ASN 数据库；网络类型为启发式推测，不证明住宅、伪家宽或广播属性'}}}catch{}}if(geo.network==='网络类型待核验')geo.network=networkType(geo.operator);
if(!Number.isFinite(geo.latitude)||Math.abs(geo.latitude)>90){delete geo.latitude;delete geo.longitude}if(!Number.isFinite(geo.longitude)||Math.abs(geo.longitude)>180){delete geo.latitude;delete geo.longitude}return geo}
