'use client';
import {Server,trafficAmount,countryName,bytes,online,health,trafficUsed,unlimited,duration,networkLabel,nextTrafficReset} from '@/lib/model';
import {Flag,OsIcon} from './icons';
import {SegmentBar} from './segmented';
import {PriceBadge,ExpiryBadge,ProbeHistory,RateActivity} from './telemetry';
import {Cpu,MemoryStick,HardDrive,Activity,Settings2,ArrowUp,ArrowDown,ShieldCheck,Clock,Network} from 'lucide-react';
import {Sample} from '@/lib/telemetry';
export function ListHead(){return <div className="node-table-head"><span>节点</span><span>系统</span><span>CPU</span><span>内存</span><span>磁盘</span><span>负载</span><span>实时</span><span>累计流量</span><span>网络</span><span>在线 / 到期</span></div>}
export default function DenseCard({s,mode,open,edit,settings,history=[],now,readOnly,sort,move,onDrag,onDrop}:{s:Server;mode:'compact'|'mini'|'list';open:()=>void;edit:()=>void;settings:any;history?:Sample[];now:number;readOnly?:boolean;sort:boolean;move:(n:number)=>void;onDrag:()=>void;onDrop:()=>void}){
 const m=s.metrics,ok=online(s,settings.offline),h=health(s,settings),used=trafficUsed(s),inf=unlimited(s.meta),quota=s.meta.quota*1024**3,checks=m?.checks||[],up=m?duration(m.uptime+(ok?Math.max(0,now-s.seen):0)).replace(/ \d+秒$/, ''):'待接入';
 const metrics=[{name:'CPU',value:m?.cpu,color:'blue',Icon:Cpu,limit:settings.cpu},{name:'内存',value:m?.memory,color:'purple',Icon:MemoryStick,limit:settings.memory},{name:'磁盘',value:m?.disk,color:'amber',Icon:HardDrive,limit:settings.disk},{name:'负载',value:m?Math.min(100,m.load/m.cores*100):undefined,color:'pink',Icon:Activity,limit:100}];
 const metric=(item:typeof metrics[number])=><div className={'dense-metric tone-'+item.color} key={item.name}><span><item.Icon size={12}/>{item.name}<b>{item.value===undefined?'—':item.name==='负载'?m!.load.toFixed(2):item.value.toFixed(1)+'%'}</b></span><SegmentBar count={mode==='mini'?14:mode==='list'?16:18} value={item.value??0} color={item.color} threshold={item.limit}/></div>;
 const identity=<div className="dense-identity"><Flag code={s.meta.country}/><button onClick={open} title={s.meta.name}>{s.meta.name}</button></div>;
 const os=<button className="dense-os" onClick={open} aria-label={`${s.meta.name} 系统详情`} title={s.meta.osOverride||m?.os||'系统详情'}><OsIcon size={20} os={s.meta.osOverride||m?.os}/></button>;
 const actions=sort?<span className="dense-actions"><button aria-label="上移" onClick={()=>move(-1)}><ArrowUp size={13}/></button><button aria-label="下移" onClick={()=>move(1)}><ArrowDown size={13}/></button></span>:!readOnly?<button className="dense-edit" onClick={edit} aria-label={`编辑 ${s.meta.name}`}><Settings2 size={13}/></button>:null;
 if(mode==='list')return <article className={`node-table-row glass ${ok?'':'node-offline'}`} draggable={sort} onDragStart={onDrag} onDragOver={e=>e.preventDefault()} onDrop={onDrop}><div>{identity}<PriceBadge meta={s.meta}/>{actions}</div><div>{os}<small>{m?.os||'待识别'}</small></div>{metrics.map(metric)}<div className="dense-rates"><b>↑ {m?bytes(m.upload):'—'}/s</b><b>↓ {m?bytes(m.download):'—'}/s</b></div><div><span>↑ {m?bytes(m.tx):'—'}</span><span>↓ {m?bytes(m.rx):'—'}</span></div><button className="dense-latency" onClick={open}>{checks[0]?checks[0].ms===null?'超时':checks[0].ms.toFixed(0)+' ms':'待采样'}<SegmentBar value={checks[0]?.ms===null?100:checks[0]?Math.min(100,checks[0].ms/settings.latency*100):0} color="green"/></button><div><span className={ok?'healthy':'offline'}>{ok?up:'离线 / 待接入'}</span><ExpiryBadge meta={s.meta}/></div></article>;
 return <article className={`dense-card glass density-${mode} ${ok?'':'node-offline'}`} draggable={sort} onDragStart={onDrag} onDragOver={e=>e.preventDefault()} onDrop={onDrop}><header>{identity}{actions}{os}</header><div className="node-location" title={countryName(s.meta.country)}>{countryName(s.meta.country)}{s.meta.region&&` · ${s.meta.region.replace(/^.* · /,'')}`}</div><div className="dense-tags"><span className={ok?'healthy':'offline'}>{s.meta.maintenance?'维护':ok?'● 在线':'● 未连接'}</span>{mode==='mini'?<PriceBadge meta={s.meta}/>:<span title={networkLabel(s.meta)}>{networkLabel(s.meta)}</span>}</div><div className="dense-metrics">{metrics.map(metric)}</div>{mode==='compact'?<div className="dense-strip"><div className="dense-rates"><b>↑ {m?bytes(m.upload):'—'}/s</b><RateActivity value={m?.upload||0} history={history} field="upload" stale={!ok}/><b>↓ {m?bytes(m.download):'—'}/s</b><RateActivity value={m?.download||0} history={history} field="download" stale={!ok}/></div><div><b>↑ {m?bytes(m.tx):'—'}</b><b>↓ {m?bytes(m.rx):'—'}</b></div><div><ExpiryBadge meta={s.meta}/><PriceBadge meta={s.meta}/></div><div className="dense-connections"><span><Network size={13}/>TCP <b>{m?.tcp??'—'}</b></span><span><Network size={13}/>UDP <b>{m?.udp??'—'}</b></span></div></div>:<div className="mini-network"><div><span>↑ <b>{m?bytes(m.upload):'—'}/s</b></span><RateActivity value={m?.upload||0} history={history} field="upload" stale={!ok}/></div><span>↑ <b>{m?bytes(m.tx):'—'}</b></span><div><span>↓ <b>{m?bytes(m.download):'—'}/s</b></span><RateActivity value={m?.download||0} history={history} field="download" stale={!ok}/></div><span>↓ <b>{m?bytes(m.rx):'—'}</b></span></div>}<section className="dense-quota"><div className="quota-heading"><span>本周期流量</span><strong>{m?trafficAmount(used):'待采样'} <small>/ {inf?'∞ 无限':s.meta.trafficMode==='unknown'?'未设配额':trafficAmount(quota)}</small></strong></div>{!inf&&s.meta.trafficMode!=='unknown'&&quota>0&&<SegmentBar value={used/quota*100} color="green" threshold={settings.traffic} label="本周期流量使用率"/>}<div className="quota-reset">{nextTrafficReset(s.meta.resetDay,new Date(now*1000))}</div><div className="dense-uptime"><Clock size={13}/><span>{ok?'在线':'最后运行'}</span><b>{up}</b></div></section>{mode==='mini'&&<div className="mini-status-grid"><span>TCP <b>{m?.tcp??'—'}</b></span><span>UDP <b>{m?.udp??'—'}</b></span><span title={networkLabel(s.meta)}>{networkLabel(s.meta)}</span><ExpiryBadge meta={s.meta}/></div>}<div className="dense-probes">{checks.slice(0,3).map(p=><div key={p.name}><ProbeHistory history={history} current={p} field="ms" threshold={settings.latency}/><ProbeHistory history={history} current={p} field="loss" threshold={settings.loss}/></div>)}{!checks.length&&<small>等待线路采样</small>}</div><button className={`dense-health health-${h.level}`} title={h.text} onClick={open}><ShieldCheck size={12}/>{h.title}<span>查看详情 ›</span></button></article>;
}
