'use client';
import {useEffect,useRef,useState} from 'react';
import {Maximize2,Minimize2,Pause,Play,LocateFixed,Globe2} from 'lucide-react';
import {Server,countryName,online} from '@/lib/model';
import {Flag} from './icons';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
type V=[number,number,number];
const vector=(lat:number,lng:number):V=>{const a=lat*Math.PI/180,b=lng*Math.PI/180;return [Math.cos(a)*Math.sin(b),Math.sin(a),Math.cos(a)*Math.cos(b)]};
function arc(a:V,b:V,t:number):V{const dot=Math.max(-1,Math.min(1,a[0]*b[0]+a[1]*b[1]+a[2]*b[2])),angle=Math.acos(dot),sn=Math.sin(angle),u=sn>.001?Math.sin((1-t)*angle)/sn:1-t,v=sn>.001?Math.sin(t*angle)/sn:t,lift=1+Math.sin(t*Math.PI)*(.12+angle*.12);return [(a[0]*u+b[0]*v)*lift,(a[1]*u+b[1]*v)*lift,(a[2]*u+b[2]*v)*lift]}
export default function Globe({servers,hubId,onHub,light=false,motion=true,onOpen}:{servers:Server[];hubId:string;onHub:(id:string)=>void;light?:boolean;motion?:boolean;onOpen:(s:Server)=>void}){const canvas=useRef<HTMLCanvasElement>(null),wrap=useRef<HTMLDivElement>(null),rotation=useRef(-.7),drag=useRef<{x:number;y:number;move:boolean}|null>(null),tilt=useRef(.22),hits=useRef<{x:number;y:number;s:Server}[]>([]),[land,setLand]=useState<number[][][]>([]),[dots,setDots]=useState<number[][]>([]),[paused,setPaused]=useState(false),[large,setLarge]=useState(false),[hover,setHover]=useState<Server|null>(null),[assetError,setAssetError]=useState(false);
const nodes=servers.filter(s=>typeof s.meta.latitude==='number'&&typeof s.meta.longitude==='number'),hub=nodes.find(s=>s.id===hubId)||nodes[0];
useEffect(()=>{Promise.all([fetch('/maps/land.json').then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('/maps/land-dots.json').then(r=>{if(!r.ok)throw Error();return r.json()})]).then(([a,b])=>{setLand(a as number[][][]);setDots(b as number[][])}).catch(()=>setAssetError(true))},[]);
useEffect(()=>{if(!large)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setLarge(false)};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=before;window.removeEventListener('keydown',key)}},[large]);
useEffect(()=>{const el=canvas.current;if(!el)return;const ctx=el.getContext('2d');if(!ctx)return;let w=700,h=470,raf=0,last=0;const resize=()=>{const b=el.getBoundingClientRect();w=b.width;h=b.height;const dpr=Math.min(2,window.devicePixelRatio||1);el.width=w*dpr;el.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)};const ro=new ResizeObserver(resize);ro.observe(el);resize();const images:Record<string,HTMLImageElement>={};for(const s of nodes){const im=new Image();im.src=`/flags/${s.meta.country.toLowerCase()}.svg`;images[s.meta.country]=im}const coast=land.map(r=>r.map(([lng,lat])=>vector(lat,lng))),points=dots.map(([lng,lat])=>vector(lat,lng));const draw=(time:number)=>{const delta=Math.min(50,time-last);last=time;if(!paused&&motion&&!drag.current)rotation.current+=delta*.000055;const r=Math.min(w*.35,h*.4),cx=w*.5,cy=h*.5,rot=rotation.current,at=tilt.current;const project=(p:V)=>{const x=p[0]*Math.cos(rot)+p[2]*Math.sin(rot),z=-p[0]*Math.sin(rot)+p[2]*Math.cos(rot),y=p[1]*Math.cos(at)-z*Math.sin(at),depth=p[1]*Math.sin(at)+z*Math.cos(at);return {x:cx+x*r,y:cy-y*r,z:depth}};ctx.clearRect(0,0,w,h);
 const halo=ctx.createRadialGradient(cx,cy,r*.75,cx,cy,r*1.25);halo.addColorStop(0,'transparent');halo.addColorStop(.65,light?'rgba(93,78,183,.12)':'rgba(122,101,255,.11)');halo.addColorStop(1,'transparent');ctx.fillStyle=halo;ctx.fillRect(0,0,w,h);
 const bg=ctx.createRadialGradient(cx-r*.3,cy-r*.45,0,cx,cy,r);bg.addColorStop(0,light?'#c1d4ef':'#152c52');bg.addColorStop(.6,light?'#e3eaf6':'#0e1934');bg.addColorStop(1,light?'#b2c9e8':'#070e20');ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fillStyle=bg;ctx.fill();ctx.strokeStyle=light?'#9eafd3':'#647bc942';ctx.lineWidth=1;ctx.stroke();
 const line=(arr:V[],color:string,width=1)=>{ctx.beginPath();let started=false;for(const v of arr){const p=project(v);if(p.z<0){started=false;continue}if(!started){ctx.moveTo(p.x,p.y);started=true}else ctx.lineTo(p.x,p.y)}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()};
 for(let lat=-60;lat<=60;lat+=30)line(Array.from({length:121},(_,i)=>vector(lat,-180+i*3)),light?'#5f7ea325':'#849ac815',.7);
 for(let lng=0;lng<360;lng+=30)line(Array.from({length:61},(_,i)=>vector(-90+i*3,lng)),light?'#5f7ea325':'#849ac815',.7);
 for(const ring of coast)line(ring,light?'#4e72947a':'#69b7d43b',.75);
 for(const v of points){const p=project(v);if(p.z<0)continue;ctx.fillStyle=light?`rgba(40,103,116,${.2+p.z*.4})`:`rgba(115,192,214,${.13+p.z*.43})`;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.45,r/180),0,Math.PI*2);ctx.fill()}
 if(hub){const b=vector(hub.meta.latitude!,hub.meta.longitude!);for(let i=0;i<nodes.length;i++){const s=nodes[i];if(s.id===hub.id)continue;const a=vector(s.meta.latitude!,s.meta.longitude!);const arr=Array.from({length:65},(_,n)=>arc(a,b,n/64));line(arr,online(s)?(light?'#aa59ce88':'#d782f0aa'):'#78819955',1.15);const t=motion&&!paused?((time*.00012+i*.13)%1):.5,p=project(arc(a,b,t));if(p.z>0){ctx.beginPath();ctx.arc(p.x,p.y,2.3,0,Math.PI*2);ctx.shadowColor='#d7a2ff';ctx.shadowBlur=9;ctx.fillStyle=light?'#983be1':'#f4b7ff';ctx.fill();ctx.shadowBlur=0}}}
 hits.current=[];for(const s of nodes){const p=project(vector(s.meta.latitude!,s.meta.longitude!));if(p.z<0)continue;const selected=s.id===hub?.id;ctx.beginPath();ctx.arc(p.x,p.y,selected?7:4,0,Math.PI*2);ctx.fillStyle=selected?'#faf0ff':online(s)?'#82edcb':'#a0a8bc';ctx.shadowColor=selected?'#d4a5ff':'#68d6bd';ctx.shadowBlur=selected?18:9;ctx.fill();ctx.shadowBlur=0;const im=images[s.meta.country];if(im?.complete&&im.naturalWidth){ctx.drawImage(im,p.x+7,p.y-18,20,15)}hits.current.push({x:p.x,y:p.y,s})}
 raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);ro.disconnect()}},[servers,hubId,land,dots,light,motion,paused,large]);
const pointer=(e:React.PointerEvent<HTMLCanvasElement>)=>{const b=e.currentTarget.getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top;if(drag.current){const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;if(Math.abs(dx)+Math.abs(dy)>2)drag.current.move=true;rotation.current+=dx*.007;tilt.current=Math.max(-1,Math.min(1,tilt.current+dy*.005));drag.current.x=e.clientX;drag.current.y=e.clientY}else setHover(hits.current.find(p=>Math.hypot(p.x-x,p.y-y)<26)?.s||null)};
return <section className={`globe-panel glass ${large?'globe-fullscreen':''}`} ref={wrap} role={large?'dialog':undefined} aria-modal={large||undefined} aria-label="全球节点地球"><div className="globe-heading"><div><span className="eyebrow">GLOBAL NETWORK</span><h2><Globe2 size={18}/>全球节点拓扑</h2></div><div className="globe-controls"><button className="icon-btn" aria-label={paused?'旋转地球':'暂停旋转'} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button className="icon-btn" aria-label="居中汇聚主机" onClick={()=>{if(hub){rotation.current=-hub.meta.longitude!*Math.PI/180;tilt.current=hub.meta.latitude!*Math.PI/180}}}><LocateFixed size={17}/></button><button className="icon-btn" aria-label={large?'退出地球全屏':'展开地球'} onClick={()=>setLarge(!large)}>{large?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</button></div></div><div className="globe-map"><div className="globe-count"><strong>{nodes.length}</strong><span>已定位节点</span></div><canvas ref={canvas} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,move:false}}} onPointerMove={pointer} onPointerUp={e=>{if(drag.current&&!drag.current.move){const b=e.currentTarget.getBoundingClientRect(),node=hits.current.find(p=>Math.hypot(p.x-e.clientX+b.left,p.y-e.clientY+b.top)<26);if(node)onOpen(node.s)}drag.current=null}} onPointerCancel={()=>drag.current=null} onPointerLeave={()=>setHover(null)} aria-label="可拖动旋转的服务器地球图"/><div className="globe-hint">{hover?<><Flag code={hover.meta.country}/><strong>{hover.meta.name}</strong><span>{hover.meta.region} · {hover.meta.locationAccuracy||'手动坐标'}</span></>:<span>{assetError?'地理底图加载失败，仍可查看节点坐标':'拖动旋转 · 点击节点查看详情 · 连线为逻辑汇聚，不代表实测路由'}</span>}</div></div><div className="globe-footer"><label>汇聚主机<NativeSelect value={hub?.id||''} onChange={e=>onHub(e.target.value)} disabled={!nodes.length}>{!nodes.length&&<NativeSelectOption value="">等待节点定位</NativeSelectOption>}{nodes.map(s=><NativeSelectOption key={s.id} value={s.id}>{s.meta.name}</NativeSelectOption>)}</NativeSelect></label><span>{servers.length-nodes.length?`${servers.length-nodes.length} 个节点待定位`:'IP 定位为近似位置，可手动修正'}</span></div></section>}
