'use client';
import {chineseRegion} from '@/lib/regions';
import {useEffect,useRef,useState} from 'react';
import {Maximize2,Minimize2,Pause,Play,LocateFixed,Globe2,Plus,Minus,Search,MapPin,Settings2,Terminal,ArrowUpRight,Route,X} from 'lucide-react';
import {Server,countryName,online,bytes,health} from '@/lib/model';
import {distanceKm,unproject,sphereVisible} from '@/lib/telemetry';
import {Flag} from './icons';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
type V=[number,number,number];
type Coord={latitude:number;longitude:number};
const vector=(lat:number,lng:number):V=>{const a=lat*Math.PI/180,b=lng*Math.PI/180;return [Math.cos(a)*Math.sin(b),Math.sin(a),Math.cos(a)*Math.cos(b)]};
function arc(a:V,b:V,t:number):V{const dot=Math.max(-1,Math.min(1,a[0]*b[0]+a[1]*b[1]+a[2]*b[2])),angle=Math.acos(dot),sn=Math.sin(angle);let v:V;if(sn<.001&&dot<0){const tangent:V=Math.abs(a[1])<.9?[-a[2],0,a[0]]:[0,a[2],-a[1]],norm=Math.hypot(...tangent);v=a.map((x,i)=>x*Math.cos(Math.PI*t)+tangent[i]/norm*Math.sin(Math.PI*t)) as V}else{const u=sn>.001?Math.sin((1-t)*angle)/sn:1-t,w=sn>.001?Math.sin(t*angle)/sn:t;v=a.map((x,i)=>x*u+b[i]*w) as V}const lift=1+Math.sin(t*Math.PI)*(.12+angle*.12);return v.map(x=>x*lift) as V}
const located=(s:Server)=>typeof s.meta.latitude==='number'&&typeof s.meta.longitude==='number';
export default function Globe({readOnly=false,servers,hubId,onHub,light=false,motion=true,onOpen,onEdit,onInstall,settings}:{readOnly?:boolean;servers:Server[];hubId:string;onHub:(id:string)=>void;light?:boolean;motion?:boolean;onOpen:(s:Server)=>void;onEdit:(s:Server)=>void;onInstall:(s:Server)=>void;settings:any}){
 const canvas=useRef<HTMLCanvasElement>(null),wrap=useRef<HTMLElement>(null),flowPhase=useRef(0),rotation=useRef(-.7),tilt=useRef(.22),zoomRef=useRef(1),view=useRef({w:700,h:470,r:180,cx:350,cy:235}),drag=useRef<{x:number;y:number;startX:number;startY:number;move:boolean}|null>(null),hits=useRef<{x:number;y:number;s:Server}[]>([]),[land,setLand]=useState<number[][][]>([]),[dots,setDots]=useState<number[][]>([]),[paused,setPaused]=useState(false),[large,setLarge]=useState(false),[hover,setHover]=useState<Server|null>(null),[assetError,setAssetError]=useState(false),[zoom,setZoom]=useState(1),[selectedId,setSelectedId]=useState(''),[query,setQuery]=useState(''),[routeMode,setRouteMode]=useState('all'),[picked,setPicked]=useState<Coord|null>(null),[clusterIds,setClusterIds]=useState<string[]>([]);
 const flagImages=useRef<Record<string,HTMLImageElement>>({});
 const nodes=servers.filter(located),hub=nodes.find(s=>s.id===hubId)||nodes[0],selected=servers.find(s=>s.id===selectedId),selectedHealth=selected?health(selected,settings):null;
 const setMagnification=(z:number)=>{const v=Math.max(.7,Math.min(3,z));zoomRef.current=v;setZoom(v)};
 const focus=(s:Server)=>{setSelectedId(s.id);setPicked(null);if(located(s)){rotation.current=-s.meta.longitude!*Math.PI/180;tilt.current=s.meta.latitude!*Math.PI/180;setPaused(true)}};
 const openNode=(s:Server)=>{focus(s);setClusterIds([]);setLarge(false);onOpen(s)};
 const routeFocus=()=>{if(!selected||!hub||!located(selected))return;const a=vector(selected.meta.latitude!,selected.meta.longitude!),b=vector(hub.meta.latitude!,hub.meta.longitude!),v=arc(a,b,.5);rotation.current=-Math.atan2(v[0],v[2]);tilt.current=Math.asin(v[1]/Math.hypot(...v));setMagnification(1);setPaused(true);setRouteMode('selected')};
 useEffect(()=>{Promise.all([fetch('/maps/land.json').then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('/maps/land-dots.json').then(r=>{if(!r.ok)throw Error();return r.json()})]).then(([a,b])=>{setLand(a as number[][][]);setDots(b as number[][])}).catch(()=>setAssetError(true))},[]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const wheel=(e:WheelEvent)=>{if(document.activeElement===c||e.ctrlKey){e.preventDefault();setMagnification(zoomRef.current-e.deltaY*.002)}};c.addEventListener('wheel',wheel,{passive:false});return()=>c.removeEventListener('wheel',wheel)},[]);
 useEffect(()=>{if(!large)return;const before=document.body.style.overflow,previous=document.activeElement as HTMLElement;document.body.style.overflow='hidden';wrap.current?.querySelector<HTMLButtonElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setLarge(false);if(e.key==='Tab'){const all=Array.from(wrap.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,[tabindex="0"]')||[]).filter(el=>el.getClientRects().length);const first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=before;window.removeEventListener('keydown',key);previous?.focus()}},[large]);
 useEffect(()=>{const el=canvas.current;if(!el)return;const ctx=el.getContext('2d');if(!ctx)return;let w=700,h=470,raf=0,last=0,pixelRatio=1;const resize=()=>{const b=el.getBoundingClientRect();w=b.width;h=b.height;const dpr=Math.min(4,Math.max(1,window.devicePixelRatio||1));pixelRatio=dpr;const width=Math.round(w*dpr),height=Math.round(h*dpr);if(el.width!==width||el.height!==height){el.width=width;el.height=height}ctx.setTransform(width/Math.max(1,w),0,0,height/Math.max(1,h),0,0);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high'};const ro=new ResizeObserver(resize);ro.observe(el);resize();const images=flagImages.current;for(const s of nodes){if(images[s.meta.country])continue;const im=new Image();im.src=`/flags/${s.meta.country.toLowerCase()}.svg`;images[s.meta.country]=im}const coast=land.map(r=>r.map(([lng,lat])=>vector(lat,lng))),points=dots.map(([lng,lat])=>vector(lat,lng));
 const routePaths=hub?nodes.map(s=>({s,arr:Array.from({length:161},(_,n)=>arc(vector(s.meta.latitude!,s.meta.longitude!),vector(hub.meta.latitude!,hub.meta.longitude!),n/160))})):[];
 const draw=(time:number)=>{if(pixelRatio!==Math.min(4,Math.max(1,window.devicePixelRatio||1)))resize();const delta=Math.min(50,time-last);last=time;if(!paused&&motion&&!drag.current){rotation.current+=delta*.000055}if(motion)flowPhase.current=(flowPhase.current+delta*.00012)%1;const r=Math.min(w*.38,h*.39)*zoomRef.current,cx=w*.5,cy=h*.49,rot=rotation.current,at=tilt.current;view.current={w,h,r,cx,cy};const project=(p:V)=>{const x=p[0]*Math.cos(rot)+p[2]*Math.sin(rot),z=-p[0]*Math.sin(rot)+p[2]*Math.cos(rot),y=p[1]*Math.cos(at)-z*Math.sin(at),depth=p[1]*Math.sin(at)+z*Math.cos(at);return {x:cx+x*r,y:cy-y*r,z:depth}};ctx.clearRect(0,0,w,h);
 const halo=ctx.createRadialGradient(cx,cy,r*.75,cx,cy,r*1.22);halo.addColorStop(0,'transparent');halo.addColorStop(.7,light?'rgba(82,123,190,.15)':'rgba(104,123,248,.14)');halo.addColorStop(1,'transparent');ctx.fillStyle=halo;ctx.fillRect(0,0,w,h);
 const bg=ctx.createRadialGradient(cx-r*.3,cy-r*.45,0,cx,cy,r);bg.addColorStop(0,light?'rgba(164,205,230,.8)':'rgba(28,55,90,.8)');bg.addColorStop(.55,light?'rgba(207,230,245,.8)':'rgba(12,28,52,.88)');bg.addColorStop(1,light?'rgba(138,175,210,.8)':'rgba(5,13,30,.9)');ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fillStyle=bg;ctx.fill();ctx.strokeStyle=light?'#7093bf66':'#647bc96b';ctx.lineWidth=1;ctx.stroke();
 const line=(arr:V[],color:string,width=1)=>{ctx.beginPath();let started=false;for(const v of arr){const p=project(v);if(!sphereVisible((p.x-cx)/r,(p.y-cy)/r,p.z)){started=false;continue}if(!started){ctx.moveTo(p.x,p.y);started=true}else ctx.lineTo(p.x,p.y)}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()};
 for(let lat=-75;lat<=75;lat+=15)line(Array.from({length:181},(_,i)=>vector(lat,-180+i*2)),light?'#54759824':'#94b5d51a',.7);
 for(let lng=0;lng<360;lng+=15)line(Array.from({length:91},(_,i)=>vector(-90+i*2,lng)),light?'#54759824':'#94b5d51a',.7);
 for(const ring of coast)line(ring,light?'#39778fcc':'#74c6d7aa',1);
 for(const v of points){const p=project(v);if(p.z<0)continue;ctx.fillStyle=light?`rgba(36,118,127,${.22+p.z*.42})`:`rgba(114,195,192,${.16+p.z*.47})`;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.55,Math.min(2,r/180)),0,Math.PI*2);ctx.fill()}
 if(hub){const b=vector(hub.meta.latitude!,hub.meta.longitude!);for(let i=0;i<nodes.length;i++){const {s,arr}=routePaths[i];if(s.id===hub.id||routeMode==='selected'&&s.id!==selectedId)continue;const active=s.id===selectedId,healthy=online(s,settings.offline);line(arr,healthy?(light?'#9654c566':'#cd78e66b'):'#8c9ab52a',active?1.5:.7);if(!healthy)continue;for(let pulse=0;pulse<2;pulse++){const head=(flowPhase.current+i*.137+pulse*.5)%1;for(let k=0;k<16;k++){const t=head-k*.008;if(t<0)break;const next=Math.max(0,t-.008),alpha=(1-k/16)*.85;line([arr[Math.floor(next*160)],arr[Math.floor(t*160)]],light?`rgba(151,55,208,${alpha})`:`rgba(230,156,255,${alpha})`,active?3:1.7)}const point=project(arr[Math.floor(head*160)]);if(sphereVisible((point.x-cx)/r,(point.y-cy)/r,point.z)){ctx.beginPath();ctx.arc(point.x,point.y,active?3.2:2,0,Math.PI*2);ctx.shadowColor='#d7a2ff';ctx.shadowBlur=9;ctx.fillStyle=light?'#983be1':'#f4b7ff';ctx.fill();ctx.shadowBlur=0}}}}

 hits.current=[];for(const s of nodes){const p=project(vector(s.meta.latitude!,s.meta.longitude!));if(p.z<0)continue;const isHub=s.id===hub?.id,active=s.id===selectedId;ctx.beginPath();ctx.arc(p.x,p.y,active?8:isHub?6:3.5,0,Math.PI*2);ctx.fillStyle=active?'#f4c7ff':isHub?'#ffe7a2':online(s,settings.offline)?'#74e2bc':'#8e9bb3';ctx.shadowColor=active?'#e5a2ff':'#68d6bd';ctx.shadowBlur=active?20:8;ctx.fill();ctx.shadowBlur=0;const im=images[s.meta.country];if(im?.complete&&im.naturalWidth)ctx.drawImage(im,Math.round((p.x+9)*pixelRatio)/pixelRatio,Math.round((p.y-22)*pixelRatio)/pixelRatio,26,19.5);if(active||isHub){ctx.font='600 13px Arial';ctx.fillStyle=light?'#34415e':'#dfe8f8';ctx.textAlign='center';ctx.fillText((isHub?'◎ ':'')+s.meta.name.slice(0,24),p.x,p.y+24)}hits.current.push({x:p.x,y:p.y,s})}
 if(picked){const p=project(vector(picked.latitude,picked.longitude));if(p.z>0){ctx.strokeStyle=light?'#ca7736':'#ffd39d';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.moveTo(p.x-12,p.y);ctx.lineTo(p.x+12,p.y);ctx.moveTo(p.x,p.y-12);ctx.lineTo(p.x,p.y+12);ctx.stroke()}}
 raf=requestAnimationFrame(draw)};draw(performance.now());return()=>{cancelAnimationFrame(raf);ro.disconnect()}},[servers,hubId,land,dots,light,motion,paused,large,selectedId,routeMode,picked,settings.offline]);
 const pointer=(e:React.PointerEvent<HTMLCanvasElement>)=>{const b=e.currentTarget.getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top;if(drag.current){const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;if(Math.hypot(e.clientX-drag.current.startX,e.clientY-drag.current.startY)>5)drag.current.move=true;rotation.current+=dx*.006/zoomRef.current;tilt.current=Math.max(-Math.PI/2,Math.min(Math.PI/2,tilt.current+dy*.006/zoomRef.current));drag.current.x=e.clientX;drag.current.y=e.clientY}else setHover(hits.current.find(p=>Math.hypot(p.x-x,p.y-y)<22)?.s||null)};
 const pick=(x:number,y:number)=>{const matches=hits.current.filter(p=>Math.hypot(p.x-x,p.y-y)<14||(x>=p.x+5&&x<=p.x+38&&y>=p.y-25&&y<=p.y+1));if(matches.length===1){openNode(matches[0].s);return}if(matches.length>1){setClusterIds(matches.map(p=>p.s.id));setPaused(true);return}setClusterIds([]);const v=view.current,coord=unproject(x,y,v.cx,v.cy,v.r,rotation.current,tilt.current);if(coord){setPicked(coord);setSelectedId('');setPaused(true)}};
 const filtered=servers.filter(s=>(s.meta.name+s.meta.region+countryName(s.meta.country)+(s.meta.ip||'')).toLowerCase().includes(query.toLowerCase())),nearest=picked?nodes.map(s=>({s,km:distanceKm(picked,s.meta as Coord)})).sort((a,b)=>a.km-b.km).slice(0,3):[];
 return <section className={`globe-panel glass ${large?'globe-fullscreen':''}`} ref={wrap} role={large?'dialog':undefined} aria-modal={large||undefined} aria-label="全球节点地球"><div className="globe-heading"><div><span className="eyebrow">GLOBAL NETWORK</span><h2><Globe2 size={18}/>全球线路观察台 <span className="tag">{nodes.length} 个位置</span></h2></div><div className="globe-controls"><button className="icon-btn" aria-label="缩小地球" disabled={zoom<=.7} onClick={()=>setMagnification(zoom-.2)}><Minus size={16}/></button><span className="zoom-label">{Math.round(zoom*100)}%</span><button className="icon-btn" aria-label="放大地球" disabled={zoom>=3} onClick={()=>setMagnification(zoom+.2)}><Plus size={16}/></button><button className="icon-btn" aria-label={paused?'继续旋转':'暂停旋转'} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button className="icon-btn" aria-label="重置并定位汇聚主机" onClick={()=>{setMagnification(1);if(hub)focus(hub)}}><LocateFixed size={17}/></button><button className="icon-btn" aria-label={large?'退出地球全屏':'展开地球'} onClick={()=>setLarge(!large)}>{large?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</button></div></div>
 <div className="globe-workspace"><div className="globe-map"><div className="globe-count"><strong>{servers.filter(s=>online(s,settings.offline)).length}<small> / {servers.length}</small></strong><span>在线节点 · {nodes.length} 个已定位</span></div><canvas ref={canvas} tabIndex={0} onPointerDown={e=>{e.currentTarget.focus({preventScroll:true});e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,move:false}}} onPointerMove={pointer} onPointerUp={e=>{if(drag.current&&!drag.current.move){const b=e.currentTarget.getBoundingClientRect();pick(e.clientX-b.left,e.clientY-b.top)}drag.current=null}} onPointerCancel={()=>drag.current=null} onPointerLeave={()=>setHover(null)} onDoubleClick={()=>setMagnification(zoomRef.current+.3)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-',' ','Enter'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')rotation.current-=.1;if(e.key==='ArrowRight')rotation.current+=.1;if(e.key==='ArrowUp')tilt.current=Math.min(Math.PI/2,tilt.current+.1);if(e.key==='ArrowDown')tilt.current=Math.max(-Math.PI/2,tilt.current-.1);if(['+','='].includes(e.key))setMagnification(zoomRef.current+.2);if(e.key==='-')setMagnification(zoomRef.current-.2);if(e.key===' ')setPaused(!paused);if(e.key==='Enter')pick(view.current.cx,view.current.cy)}} aria-label="地球：拖动旋转，点击选点，聚焦后滚轮缩放；方向键旋转，加减键缩放，Enter 选取中心"/>{clusterIds.length>1&&<div className="globe-node-picker" role="group" aria-label="选择重叠位置的节点"><header><strong>此位置有 {clusterIds.length} 个节点</strong><button className="icon-btn" aria-label="关闭节点选择" onClick={()=>setClusterIds([])}><X size={15}/></button></header>{servers.filter(s=>clusterIds.includes(s.id)).map(s=><button key={s.id} onClick={()=>openNode(s)}><Flag code={s.meta.country}/>{s.meta.name}<ArrowUpRight size={14}/></button>)}</div>}<div className="globe-hint">{hover?<><Flag code={hover.meta.country}/><strong>{hover.meta.name}</strong><span>{chineseRegion(hover.meta.region)||countryName(hover.meta.country)}</span></>:<span>{assetError?'底图加载失败，可继续观察节点坐标':'点击任意地点选点 · 拖动旋转 · 点击后滚轮缩放 · 双击放大'}</span>}</div><div className="globe-legend"><span><i className="legend-hub"/>汇聚主机</span><span><i className="legend-node"/>在线节点</span><span><i className="legend-route"/>流动连接示意 · 非实测路由</span></div></div>
 <aside className="globe-directory"><div className="directory-heading"><h3><Route size={16}/>节点与线路</h3><span>{servers.length}</span></div><label className="directory-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索节点 / IP / 地区" aria-label="搜索地球节点"/></label><Tabs value={routeMode} onValueChange={v=>{if(v==='selected'){const node=selected&&selected.id!==hub?.id&&located(selected)?selected:nodes.find(n=>n.id!==hub?.id);if(node)focus(node)}setRouteMode(v)}}><TabsList><TabsTrigger value="all">全部线路</TabsTrigger><TabsTrigger value="selected" disabled={!nodes.some(n=>n.id!==hub?.id)}>关注线路</TabsTrigger></TabsList></Tabs><div className="globe-server-scroll" tabIndex={0} aria-label="地球服务器列表">{filtered.map(s=><button key={s.id} className={`globe-server-row ${s.id===selectedId?'selected':''}`} onClick={()=>focus(s)} aria-pressed={s.id===selectedId}><Flag code={s.meta.country}/><div><strong>{s.meta.name}</strong><span>{s.id===hub?.id?'◎ 汇聚 · ':''}{chineseRegion(s.meta.region)||countryName(s.meta.country)}</span><small>{located(s)?`${s.meta.latitude!.toFixed(2)}°, ${s.meta.longitude!.toFixed(2)}°`:'尚未定位 · 可编辑补充'}</small></div><i className={online(s,settings.offline)?'node-online':'node-offline'}/></button>)}{!filtered.length&&<p className="form-note">没有匹配节点</p>}</div>
 {picked?<div className="globe-selection"><h3><MapPin size={15}/>选中地点<button className="icon-btn" aria-label="清除选点" onClick={()=>setPicked(null)}><X size={14}/></button></h3><p className="coordinate-value">{picked.latitude.toFixed(3)}° / {picked.longitude.toFixed(3)}°</p><small>最近节点 · 球面直线距离，非网络延迟</small>{nearest.map(({s,km})=><button className="nearest-node" key={s.id} onClick={()=>focus(s)}><Flag code={s.meta.country}/>{s.meta.name}<b>{Math.round(km).toLocaleString()} km</b></button>)}</div>:selected?<div className="globe-selection"><h3><Flag code={selected.meta.country}/>{selected.meta.name}</h3><p className="selected-ip">{readOnly?'公开监控 · IP 已隐藏':selected.meta.ip||'IP 待识别'}</p><div className="selected-telemetry"><span>CPU <b>{selected.metrics?selected.metrics.cpu.toFixed(1)+'%':'—'}</b></span><span>↑ <b>{selected.metrics?bytes(selected.metrics.upload)+'/s':'—'}</b></span></div><p className={`selected-health health-${selectedHealth?.level}`}>{selectedHealth?.title}</p>{hub&&located(selected)&&selected.id!==hub.id&&<button className="route-inspect" onClick={routeFocus}><Route size={14}/>{selected.meta.name} → {hub.meta.name}<small>{Math.round(distanceKm(selected.meta as Coord,hub.meta as Coord)).toLocaleString()} km · 地理距离</small></button>}<div className="node-actions"><button onClick={()=>{setLarge(false);onOpen(selected)}}><ArrowUpRight size={14}/>详情</button>{!readOnly&&<><button onClick={()=>{setLarge(false);onEdit(selected)}}><Settings2 size={14}/>编辑</button><button onClick={()=>{setLarge(false);onInstall(selected)}}><Terminal size={14}/>部署</button></>}</div></div>:<div className="globe-selection"><MapPin size={20}/><p>选择一个节点，查看资源与汇聚线路。</p><small>也可以点击地球任意位置，查看坐标及附近节点。</small></div>}</aside></div>
 <div className="globe-footer"><label>汇聚主机<NativeSelect value={hub?.id||''} onChange={e=>onHub(e.target.value)} disabled={!nodes.length}>{!nodes.length&&<NativeSelectOption value="">等待定位</NativeSelectOption>}{nodes.map(s=><NativeSelectOption key={s.id} value={s.id}>{s.meta.name}</NativeSelectOption>)}</NativeSelect></label><span>{servers.length-nodes.length?`${servers.length-nodes.length} 个节点待定位 · `:''}IP 位置仅为近似，连线为地理示意</span></div></section>
}
