'use client';
import {useState} from 'react';
import {Trash2,History,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {request} from '@/lib/client';
const labels:Record<string,string>={events:'状态事件',billing:'账单记录',audit:'操作记录',samples:'监控采样',analyses:'诊断结果缓存'};
export function HistoryManager({kind='events',server,demo,onChanged}:{kind?:string;server?:string;demo:boolean;onChanged:()=>Promise<unknown>}){
 const [open,setOpen]=useState(false),[category,setCategory]=useState(kind),[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[more,setMore]=useState(false);
 const query=(k:string)=>'records?kind='+k+(server?'&server='+encodeURIComponent(server):'');
 async function load(k=category,append=false){if(demo){setRows([]);setMore(false);return}const got=await request(query(k)+'&offset='+(append?rows.length:0));setRows(old=>append?[...old,...got]:got);setMore(got.length===100)}
 async function run(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function remove(id?:string,allKinds=false){const scope=allKinds?'所有类别的历史记录':labels[category];if(!window.confirm(id?'永久删除这条记录？无法撤销。':`永久清空${server?'当前节点':'当前账号'}的${scope}？包括未加载记录，无法撤销。节点、套餐、当前指标及告警规则不变；后续采样会继续产生。删除待推送事件会取消尚未开始的推送，已发出的 Telegram 消息不会撤回。`))return;await run(async()=>{await request(query(allKinds?'all':category),'DELETE',id?{id}:{all:true,before:Math.floor(Date.now()/1000)});await load();await onChanged()})}
 return <><button className="secondary history-manage-button" onClick={()=>{setOpen(true);run(()=>load())}}><History size={15}/>管理 / 删除记录</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="prism-dialog wide-dialog"><DialogTitle>{server?'当前节点':'当前账号'}记录管理</DialogTitle><p className="form-note">按类别浏览并删除。账单记录与操作记录分别管理；诊断缓存不是历次 AI 对话。清除采样后图表从新采样重新累计，当前流量账期计数不变。</p><div className="history-toolbar"><NativeSelect aria-label="记录类别" value={category} disabled={busy} onChange={e=>{setCategory(e.target.value);run(()=>load(e.target.value))}}>{Object.entries(labels).map(([k,v])=><NativeSelectOption value={k} key={k}>{v}</NativeSelectOption>)}</NativeSelect><button className="secondary" disabled={busy} onClick={()=>run(()=>load())}><RefreshCw size={15}/>刷新</button><button className="danger" disabled={busy||demo} onClick={()=>remove()}><Trash2 size={15}/>清空此类</button><button className="danger" disabled={busy||demo} onClick={()=>remove(undefined,true)}><Trash2 size={15}/>一键清空全部记录</button></div>{error&&<p role="alert" className="critical-text">{error}</p>}<div className="records-scroll history-manager-list" tabIndex={0}>{rows.map(row=><div className="event-row" key={row.id}><div><strong>{row.title}</strong><small>{new Date(row.time*1000).toLocaleString('zh-CN')} · {row.server||'平台'}</small><p>{row.detail}</p></div><button className="danger" disabled={busy||demo} onClick={()=>remove(row.id)} aria-label={'删除 '+row.title+' '+row.id}><Trash2 size={15}/>删除</button></div>)}{!rows.length&&<p className="empty">{busy?'正在加载…':demo?'演示模式不操作真实记录':'暂无记录'}</p>}{more&&<button className="secondary" disabled={busy} onClick={()=>run(()=>load(category,true))}>加载更多</button>}</div></DialogContent></Dialog></>
}
