'use client';
import {useEffect,useState} from 'react';
import {CheckCircle2,Copy,Loader2,RefreshCw,Terminal,ExternalLink} from 'lucide-react';
import {Server} from '@/lib/model';
import {request} from '@/lib/client';
import {Input} from '@/components/ui/input';
const quote=(value:string)=>"'"+value.replace(/'/g,"'\\''")+"'";
export default function InstallPanel({server,demo,authMode,notify,onConnected}:{server:Server;demo:boolean;authMode:string;notify:(text:string)=>void;onConnected:()=>void}){const [endpoint,setEndpoint]=useState(''),[ticket,setTicket]=useState(''),[expires,setExpires]=useState(0),[now,setNow]=useState(Date.now()/1000),[error,setError]=useState(''),[busy,setBusy]=useState(false),[created,setCreated]=useState(0),[enrollmentId,setEnrollmentId]=useState(''),[connected,setConnected]=useState(false);const available=!demo&&authMode==='token';useEffect(()=>{setEndpoint(window.location.origin);const t=setInterval(()=>setNow(Date.now()/1000),1000);return()=>clearInterval(t)},[]);useEffect(()=>{if(!created||!available||connected)return;let active=true;const t=setInterval(async()=>{if(Date.now()/1000>expires+120)return;try{const status=await request(`servers/${server.id}/enrollment?id=${enrollmentId}`);if(active&&status.redeemedAt&&status.seen>=status.redeemedAt){setConnected(true);onConnected()}}catch{}},3000);return()=>{active=false;clearInterval(t)}},[created,available,connected,server.id,enrollmentId,expires]);const command=ticket?`(prism_install_path=$(mktemp) && trap 'rm -f "$prism_install_path"' EXIT && curl -fsSL ${quote(endpoint+'/agent/install.sh')} -o "$prism_install_path" && sudo bash "$prism_install_path" ${quote(endpoint)} --enroll ${quote(ticket)})`:'';
const generate=async()=>{setBusy(true);setError('');try{const url=new URL(endpoint);if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash||url.pathname!=='/')throw Error('请填写当前后端的 HTTPS 根域名');if(url.origin!==window.location.origin)throw Error('安装凭证属于当前后端，请填写当前网站的公网根域名');setEndpoint(url.origin);const result=await request(`servers/${server.id}/enrollment`,'POST');setTicket(result.ticket);setExpires(result.expires);setCreated(result.created);setEnrollmentId(result.enrollmentId);setConnected(false)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
const copy=async()=>{try{await navigator.clipboard.writeText(command);notify('已复制此节点的一键安装命令')}catch{setError('剪贴板不可用，请选中命令手动复制。')}};
return <div className="install-panel"><div className="install-info"><Terminal size={26}/><div><strong>{server.meta.name}</strong><p>Linux · systemd 247+ · Python 3.9+ · 自动启动与开机自启</p></div></div>{!available?<div className="install-environment"><strong>{demo?'演示模式不会生成有效安装凭证':'请在自托管公网后端生成安装命令'}</strong><p>当前地址使用 ChatGPT 登录，服务器不能通过浏览器登录上报。先按部署说明发布后端，再打开对应节点的“安装探针”，即可生成可直接执行的命令。</p><a className="text-button" href="https://github.com/lxfcx/VPSBOT#install" target="_blank" rel="noreferrer">打开部署说明<ExternalLink size={14}/></a></div>:<><label>当前后端公网地址<Input value={endpoint} onChange={e=>{setEndpoint(e.target.value);setTicket('')}}/></label><p className="form-note">命令有效 15 分钟，仅可使用一次。已有探针在新命令实际执行时才会被替换；只生成命令不会中断监控。</p><button className="primary" disabled={busy} onClick={generate}>{busy?<Loader2 size={16} className="spin"/>:<RefreshCw size={16}/>} {ticket?'重新生成安装命令':'生成此节点的一键安装命令'}</button>{ticket&&<><div className="install-expiry"><span>{now<expires?`剩余 ${Math.max(0,Math.ceil((expires-now)/60))} 分钟`:'安装命令已过期，请重新生成'}</span><span>一次性授权 · 请勿转发</span></div><div className="code-box install-command"><code tabIndex={0}>{command}</code><button aria-label="复制完整安装命令" disabled={now>=expires} onClick={copy}><Copy size={18}/></button></div><button className="secondary" disabled={now>=expires} onClick={copy}><Copy size={15}/>复制完整命令</button><div className={`installation-status ${connected?'connected':''}`}>{connected?<CheckCircle2 size={19}/>:<Loader2 size={19} className="spin"/>}<div><strong>{connected?'已收到新心跳，实时监控已连接':'等待服务器执行安装命令'}</strong><p>{connected?'指标将按探针采样持续刷新。':'复制到目标服务器执行，服务会自动启动，面板每 3 秒检查接入状态。'}</p></div></div></>}</>}{error&&<p className="critical-text" role="alert">{error}</p>}<div className="install-steps"><span><b>1</b>生成并复制命令</span><span><b>2</b>目标服务器执行</span><span><b>3</b>自动启动，收到心跳</span></div><p className="form-note">安装完成后目标每 3 秒上报（网络异常时退避重试）。若迟迟没有心跳，可执行 <code>systemctl status prism-agent</code> 检查服务，并确认服务器能够访问当前后端。</p></div>}
