'use client';
import {useState} from 'react';
import {LockKeyhole,Loader2,ShieldCheck} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {request} from '@/lib/client';
export default function LoginScreen({changeRequired=false,onDone}:{changeRequired?:boolean;onDone:()=>Promise<void>}){
 const [username,setUsername]=useState('admin'),[password,setPassword]=useState(changeRequired?'123456':''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(changeRequired){if(next!==confirm)throw Error('两次新密码不一致');await request('auth/password','POST',{username,password:next,currentPassword:password});sessionStorage.removeItem('prism-admin')}else{await request('auth/login','POST',{username,password});sessionStorage.removeItem('prism-admin')}setPassword('');setNext('');setConfirm('');await onDone()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="app-shell theme-dark auth-shell"><section className="auth-intro"><span className="eyebrow">GLOBAL VPS OBSERVATORY</span><h2>每一次心跳，<br/>都清晰可见。</h2><p>连接全球节点，掌握资源、线路与服务状态。</p><div className="auth-features"><article>🌍<strong>全球节点</strong><span>地球线路 · 国家与运营商</span></article><article>📊<strong>实时监控</strong><span>CPU · 内存 · 磁盘 · 流量</span></article><article>🩺<strong>本地故障诊断</strong><span>无需 API Key · 阈值与恢复检测</span></article><article>🔔<strong>状态通知</strong><span>Telegram 告警与恢复推送</span></article></div><small>登录后查看真实节点数据与事件记录</small></section><form className="glass auth-card" onSubmit={submit}><div className="auth-emblem"><ShieldCheck size={30}/></div><h1>全球VPS联动观察</h1><p>{changeRequired?'首次登录，请先修改默认密码':'登录你的服务器监控面板'}</p><label>账号<Input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} minLength={3} maxLength={64} required/></label><label>{changeRequired?'当前密码':'密码'}<Input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{changeRequired&&<><label>新密码<Input type="password" autoComplete="new-password" placeholder="输入新密码（非空即可）" value={next} onChange={e=>setNext(e.target.value)} required/></label><label>确认新密码<Input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label></>}{error&&<p role="alert" className="critical-text">{error}</p>}<button className="primary" type="submit" disabled={busy}>{busy?<Loader2 size={17} className="spin"/>:<LockKeyhole size={17}/>} {changeRequired?'保存新账号密码，重新登录':'登录面板'}</button><small>账号与密码可在登录后的个人信息中修改。</small><footer><a href="https://github.com/lxfcx/VPSBOT">lxfcx</a> · <a href="https://t.me/LXFCX6">@LXFCX6</a></footer></form></div>
}
