'use client';
import NodeDetail from './node-detail';
import {ListHead} from '@/components/prism/dense-card';
import {useEffect,useState,useRef} from 'react';
import {LogIn,Sun,Moon,RefreshCw,Search} from 'lucide-react';
import {Server,defaults,defaultProfile,countryName,online,expiryDays} from '@/lib/model';
import {request} from '@/lib/client';
import {Sample,Trends,addSample,sampleOf} from '@/lib/telemetry';
import Card from './server-card';
import FleetSummary from './fleet-summary';
import {Layout,LayoutCycle} from './layout-cycle';
import Globe from './globe';
import {Flag} from './icons';
export default function PublicDashboard({onLogin,authenticated=false}:{onLogin:()=>void;authenticated?:boolean}){
 const refreshing=useRef(false);
 const [showGlobe,setShowGlobe]=useState(false),[hub,setHub]=useState('');
 const [servers,setServers]=useState<Server[]>([]),[settings,setSettings]=useState<any>(defaults),[profile,setProfile]=useState<any>(defaultProfile),[layout,setLayout]=useState<Layout>('compact'),[light,setLight]=useState(false),[q,setQ]=useState(''),[country,setCountry]=useState(''),[group,setGroup]=useState(''),[sort,setSort]=useState('default'),[selected,setSelected]=useState(''),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[updated,setUpdated]=useState(''),[trends,setTrends]=useState<Trends>({}),[now,setNow]=useState(Date.now()/1000);
 function selectNode(id:string){setSelected(id);window.history.pushState(null,'',id?'#node='+encodeURIComponent(id):window.location.pathname+window.location.search)}
 useEffect(()=>{const sync=()=>{const h=window.location.hash;try{setSelected(h.startsWith('#node=')?decodeURIComponent(h.slice(6)):'')}catch{setSelected('')}};sync();window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync)},[]);
 async function refresh(){if(refreshing.current)return;refreshing.current=true;try{const data=await request('public/dashboard');setServers(data.servers);setSettings({...defaults,...data.settings});setProfile(data.profile);setTrends(previous=>{const next:Trends={};for(const s of data.servers){const p=sampleOf(s);next[s.id]=p?addSample(previous[s.id]||[],p):previous[s.id]||[]}return next});setError('');setUpdated(new Date().toLocaleTimeString('zh-CN'))}catch(e:any){setError(e.message)}finally{refreshing.current=false;setLoaded(true)}}
 useEffect(()=>{const l=localStorage.getItem('prism-layout');if(l==='large'||l==='compact'||l==='mini'||l==='list')setLayout(l);setLight(localStorage.getItem('prism-theme')==='light');refresh();const t=setInterval(refresh,3000),clock=setInterval(()=>setNow(Date.now()/1000),1000);return()=>{clearInterval(t);clearInterval(clock)}},[]);
 useEffect(()=>{document.title=profile.documentTitle;document.documentElement.dataset.theme=light?'light':'dark'},[profile,light]);
 const filtered=servers.filter(s=>(!country||s.meta.country===country)&&(!group||s.meta.group===group)&&(!q||`${s.meta.name} ${s.meta.operator} ${countryName(s.meta.country)}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>sort==='name'?a.meta.name.localeCompare(b.meta.name,'zh-CN'):sort==='speed'?((online(b,settings.offline)?(b.metrics?.upload||0)+(b.metrics?.download||0):0)-(online(a,settings.offline)?(a.metrics?.upload||0)+(a.metrics?.download||0):0)):sort==='expiry'?(expiryDays(a.meta)??Infinity)-(expiryDays(b.meta)??Infinity):a.position-b.position),picked=servers.find(s=>s.id===selected);
 const card=(s:Server,mode:Layout)=> <Card key={s.id} s={s} mode={mode} readOnly settings={settings} now={now} history={trends[s.id]||[]} open={()=>selectNode(s.id)} edit={()=>selectNode(s.id)} sort={false} move={()=>{}} onDrag={()=>{}} onDrop={()=>{}}/>;
 if(picked)return <div className={`app-shell theme-${light?'light':'dark'} detail-shell`}><NodeDetail server={picked} servers={servers} settings={settings} publicView onBack={()=>selectNode('')} onSelect={s=>selectNode(s.id)}/></div>;
 return <div className={`app-shell public-shell theme-${light?'light':'dark'}`}><header className="public-header"><div><h1>{profile.platformName}</h1><span>{profile.platformSubtitle}</span></div><div><button className="secondary" onClick={()=>{setLight(!light);localStorage.setItem('prism-theme',light?'dark':'light')}} aria-label="切换日夜主题">{light?<Moon size={17}/>:<Sun size={17}/>}</button><button className="icon-btn subtle-admin" onClick={onLogin} aria-label={authenticated?"返回后台":"后台登录"} title={authenticated?"返回后台":"后台登录"}><LogIn size={16}/></button></div></header><main className="public-main"><FleetSummary servers={servers} settings={settings} publicView/>{showGlobe&&<Globe readOnly servers={servers} hubId={hub||settings.hubId} onHub={setHub} light={light} onOpen={s=>selectNode(s.id)} onEdit={()=>{}} onInstall={()=>{}} settings={settings}/ >}{error&&<div className="error-box" role="alert">{error}</div>}<div className="public-tools"><div className="public-inline-controls"><button className="secondary" aria-expanded={showGlobe} onClick={()=>setShowGlobe(!showGlobe)}>{showGlobe?'收起地球':'全球线路地球'}</button><button className="secondary" onClick={refresh}><RefreshCw size={15}/>刷新</button><span title={updated}>{error?'连接中断':loaded?'3 秒刷新':'加载中'}</span></div><div className="region-chips" aria-label="节点分组"><button aria-pressed={!group} onClick={()=>setGroup('')}>全部分组</button>{Array.from(new Set(servers.map(s=>s.meta.group))).map(g=><button key={g} aria-pressed={group===g} onClick={()=>setGroup(group===g?'':g)}>{g}</button>)}</div><div className="filter-actions"><div className="search"><Search size={15}/><input aria-label="搜索服务器" placeholder="搜索节点、地区、运营商" value={q} onChange={e=>setQ(e.target.value)}/></div><select aria-label="排序方式" value={sort} onChange={e=>setSort(e.target.value)}><option value="default">默认排序</option><option value="name">名称排序</option><option value="speed">带宽从高到低</option><option value="expiry">即将到期优先</option></select><LayoutCycle value={layout} onChange={v=>{setLayout(v);localStorage.setItem('prism-layout',v)}}/></div></div><section className="glass region-chips public-regions" aria-label="地区筛选"><button onClick={()=>setCountry('')} aria-pressed={!country}>全球 {servers.length}</button>{Array.from(new Set(servers.map(s=>s.meta.country))).map(c=><button key={c} onClick={()=>setCountry(country===c?'':c)} aria-pressed={country===c}><Flag code={c}/><span title={countryName(c)}>{c.toUpperCase()}</span><b>{servers.filter(s=>s.meta.country===c).length}</b></button>)}</section><section className={`server-grid layout-${layout}`}>{layout==='list'&&<ListHead/>}{filtered.map(s=>card(s,layout))}</section>{loaded&&!filtered.length&&<div className="glass empty">{servers.length?'没有匹配的服务器，可清除搜索或地区筛选。':'尚未接入服务器。管理员登录后可添加节点。'}</div>}<footer className="public-footer">只读监控 · 配置修改请登录后台 · 作者 lxfcx · TG @LXFCX6</footer></main></div>;
}
