'use client';
import {useId} from 'react';
import {bytes,Meta,expiryDays,expiryLabel,currencies} from '@/lib/model';
import {SegmentBar} from './segmented';
import {rateScale,Sample} from '@/lib/telemetry';
import {CalendarClock,Infinity as InfinityIcon} from 'lucide-react';
export function Sparkline({points,color='cyan',label,height=45}:{points:{time:number;value:number}[];color?:string;label:string;height?:number}){const id='chart'+useId().replace(/:/g,''),max=Math.max(1,...points.map(p=>p.value)),start=points[0]?.time||0,end=points.at(-1)?.time||start+1,xy=points.map(p=>`${((p.time-start)/Math.max(1,end-start)*296+2).toFixed(2)},${(height-3-p.value/max*(height-8)).toFixed(2)}`),d=xy.length?'M'+xy.join(' L'):'';return <div className={`sparkline spark-${color}`}><svg viewBox={`0 0 300 ${height}`} preserveAspectRatio="none" role="img" aria-label={label}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="currentColor" stopOpacity=".38"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><path d={`M0 ${height-2}H300`} stroke="currentColor" opacity=".12"/>{points.length>1?<><path d={`${d} L298 ${height} L2 ${height} Z`} fill={`url(#${id})`}/><path d={d} fill="none" stroke="currentColor" strokeWidth="1.6" vectorEffect="non-scaling-stroke"/></>:points.length===1?<circle cx="298" cy={height/2} r="2" fill="currentColor"/>:null}</svg>{points.length<2&&<span>{points.length?'等待后续采样':'暂无采样'}</span>}</div>}
export function RateGraph({value,history,field,color,stale=false}:{value:number;history:Sample[];field:'upload'|'download';color:'cyan'|'violet';stale?:boolean}){const {peak,percent}=rateScale(value,history.map(p=>p[field]));return <div className={`rate-visual ${stale?'stale':''}`}><SegmentBar value={percent} color={color==='cyan'?'blue':'purple'} count={24} threshold={101} fullLabel="达到采样峰值" label={`${field==='upload'?'上传':'下载'}相对采样峰值`}/>{history.length>1&&<Sparkline points={history.map(p=>({time:p.time,value:p[field]}))} color={color} label={`${field==='upload'?'上传':'下载'}真实采样趋势`} height={24}/>}<small>{stale?'最后采样 · 已失联':`采样峰值 ${bytes(peak)}/s`}</small></div>}
export function CurrencyIcon({code}:{code:string}){return <span className={`currency-icon currency-${code.toLowerCase()}`} title={code} aria-label={code}>{currencies[code]||code}</span>}
export function PriceBadge({meta}:{meta:Meta}){const free=meta.billingType==='free';return <span className={`price-badge price-${free?'free':meta.currency.toLowerCase()}`}><CurrencyIcon code={meta.currency}/><strong>{free?'免费':meta.price.toLocaleString('zh-CN',{maximumFractionDigits:2})}</strong><small>{free?meta.expiryMode==='never'?'永久':'套餐':meta.billingType==='one-time'?'一次性':meta.cycle===1?'/月':meta.cycle===3?'/季':meta.cycle===6?'/半年':'/年'}</small></span>}
export function ExpiryBadge({meta,threshold=7}:{meta:Meta;threshold?:number}){const d=expiryDays(meta),tone=d===null?meta.expiryMode==='never'?'forever':'unknown':d<0?'expired':d<=threshold?'urgent':d<=30?'soon':'safe';return <span className={`expiry-badge expiry-${tone}`} title={expiryLabel(meta)}>{meta.expiryMode==='never'?<InfinityIcon size={15}/>:<CalendarClock size={15}/>}<strong>{d===null?expiryLabel(meta):d<0?`逾期 ${Math.abs(d)} 天`:`${d} 天`}</strong>{d!==null&&d>=0&&<small>到期</small>}</span>}

export function ProbeHistory({history,current,field,threshold}:{history:Sample[];current:{name:string;ms:number|null;loss:number};field:'ms'|'loss';threshold:number}){const points=history.map(s=>({time:s.time,point:s.checks?.find(p=>p.name===current.name)})).filter(x=>x.point).slice(-20);const samples=points.length?points:[{time:0,point:current}],value=current[field];return <div className="probe-history"><div><span>{field==='ms'?current.name:'失败率'}</span><b className={value===null||value>=threshold?'probe-bad':value>=threshold*.5?'probe-warn':'probe-good'}>{value===null?'超时':field==='ms'?`${value.toFixed(0)} ms`:`${value.toFixed(1)}%`}</b></div><div className="probe-cells" role="img" aria-label={`${current.name} ${field==='ms'?'延迟':'失败率'}，${points.length?points.length+' 条历史采样':'仅当前采样'}`}>{Array.from({length:20},(_,i)=>{const sample=samples[i],v=sample?.point?.[field],state=v===undefined?'empty':v===null||v>=threshold?'bad':v>=threshold*.5?'warn':'good';return <i key={i} className={'sample-'+state} title={v===undefined?'尚无采样':`${sample.time?new Date(sample.time*1000).toLocaleTimeString('zh-CN'):'当前采样'} · ${v===null?'超时':v+(field==='ms'?' ms':'%')}`}/>})}</div></div>}
