import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
export const servers = sqliteTable('servers', { id: text('id').primaryKey(), owner: text('owner').notNull(), token: text('token').notNull(), position: integer('position').notNull().default(0), firstSeen: integer('first_seen').notNull().default(0), onlineSeconds: integer('online_seconds').notNull().default(0), meta: text('meta').notNull(), metrics: text('metrics'), seen: integer('seen').notNull().default(0) }, t => [index('servers_owner').on(t.owner), index('servers_token').on(t.token)]);
export const settings = sqliteTable('settings', { owner: text('owner').primaryKey(), value: text('value').notNull() });
export const samples = sqliteTable('samples', { id: text('id').primaryKey(), server: text('server').notNull(), time: integer('time').notNull(), value: text('value').notNull() }, t => [index('samples_server_time').on(t.server, t.time)]);
export const events = sqliteTable('events', { id: text('id').primaryKey(), owner: text('owner').notNull(), server: text('server').notNull(), time: integer('time').notNull(), kind: text('kind').notNull(), message: text('message').notNull(), payload: text('payload'), delivered: integer('delivered').notNull().default(0) }, t => [index('events_owner_time').on(t.owner, t.time)]);
export const alerts = sqliteTable('alerts', { id: text('id').primaryKey(), active: integer('active').notNull().default(0), since: integer('since').notNull().default(0) });

export const profiles=sqliteTable('profiles',{owner:text('owner').primaryKey(),value:text('value').notNull()});
export const accounts=sqliteTable('accounts',{owner:text('owner').primaryKey(),username:text('username').notNull().unique(),salt:text('salt').notNull(),password:text('password').notNull(),changed:integer('changed').notNull()});
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),owner:text('owner').notNull(),expires:integer('expires').notNull()},t=>[index('sessions_owner').on(t.owner)]);
export const attempts=sqliteTable('auth_attempts',{id:text('id').primaryKey(),count:integer('count').notNull().default(0),expires:integer('expires').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),owner:text('owner').notNull(),server:text('server').notNull().default(''),time:integer('time').notNull(),category:text('category').notNull(),action:text('action').notNull(),detail:text('detail').notNull()},t=>[index('audit_owner_time').on(t.owner,t.time)]);
export const analyses=sqliteTable('analyses',{server:text('server').primaryKey(),owner:text('owner').notNull(),time:integer('time').notNull().default(0),sample:integer('sample').notNull().default(0),provider:text('provider').notNull().default('rules'),text:text('text').notNull().default('')});
